name: Build and Release

on:
  push:
    tags:
      - 'helm-v*.*.*'

jobs:
  helm:
    # if: ${{ ! contains( github.event.ref, 'alpha' ) }}
    runs-on: ubuntu-latest
    # needs:
    #   - docker-admin-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Get Version
        id: get_version
        run: |
          # format version X.X.X 
          RELEASE_VERSION=`echo "${GITHUB_REF#refs/tags/}" | sed -e 's/helm-v//g' | sed -e 's/-alpha.*/.0/g'`
          echo ::set-output name=RELEASE_VERSION::${RELEASE_VERSION}
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: chrisdickinson/setup-yq@latest
      - name: Replace component version with YQ
        run:  |
          # set image tags on kdl
          # yq w -i helm/kdl/values.yaml 'adminUI.image.tag' ${{ steps.get_version.outputs.VERSION }}

          # set app version and chart version for kdl
          yq w -i helm/kdl/Chart.yaml 'appVersion' ${{ steps.get_version.outputs.VERSION }}
          yq w -i helm/kdl/Chart.yaml 'version' ${{ steps.get_version.outputs.RELEASE_VERSION }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        with:
          charts_dir: 'helm'
          charts_repo_url: 'http://charts-kdl.konstellation.io'
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # - name: Update Helm Chart
      #   run:  |
      #     curl --request POST --header "${{ secrets.NOTIFY_TOKEN }}" "${{ secrets.NOTIFY_URL }}"${{ steps.get_version.outputs.RELEASE_VERSION }} >/dev/null 2>&1

